name: C Extensions Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        
    - name: Install OpenMP (macOS)
      if: runner.os == 'macOS'
      run: brew install libomp
    
    - name: Build C extensions (Unix)
      if: runner.os != 'Windows'
      run: |
        cd whispr/c_ext
        chmod +x build_extensions.sh
        ./build_extensions.sh
      continue-on-error: false
    
    - name: Build C extensions (Windows)
      if: runner.os == 'Windows'
      run: |
        cd whispr/c_ext
        # Adjust for Windows if build_extensions.sh needs modifications
        python setup.py build_ext --inplace
      continue-on-error: false
    
    - name: Test C extensions
      run: |
        cd whispr/c_ext
        python test_extensions.py
      continue-on-error: true
    
    - name: Upload compiled extensions as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: c-extensions-${{ matrix.os }}-py${{ matrix.python-version }}
        path: |
          whispr/c_ext/*.so
          whispr/c_ext/*.pyd
          whispr/c_ext/*.dll 